server:
  port: 8082
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haigou?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://10.12.159.40:10086/eureka
